# Generated by Django 4.0.3 on 2022-06-19 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_rating_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='creator',
        ),
    ]
